coop:
  defaultCcid: sandbox/ex02
  ccid: sandbox/ex02, sandbox/ssm
  user:
    name: dfef919ef60296ca173d99f2132becde
    password: 660bd560b383333750f629362e0160f9
    org: bclan
  endorsers: peer0:bclan
  config:
    file: file:./c2-sandbox/config/fabric/config.json
    crypto: file:./c2-sandbox/config/fabric/

spring:
  main:
    web-application-type: reactive

server:
  port: 9090
