coop:
  defaultCcid: sandbox/ex02
  ccid: sandbox/ex02, sandbox/ssm
  user:
    name: ${COOP_USER_NAME}
    password: ${COOP_USER_PASSWORD}
    org: bclan
  endorsers: peer0:bclan
  config:
    file: file:./c2-sandbox/config/fabric/config.json
    crypto: file:./c2-sandbox/config/fabric/

spring:
  main:
    web-application-type: reactive

server:
  port: 9090
