version: '3.8'

services:

  cli-init-ex02.bc-coop.bclan:
    container_name: cli-init-ex02-bclan-${DOCKER_NETWORK}
    image: ghcr.io/komune-io/c2-sandbox-cli:${VERSION_C2}
    command: /opt/c2-sandbox/chaincode/ex02/init.sh
    networks:
      - net

networks:
  net:
    name: ${DOCKER_NETWORK}
    external: true
