version: '3.7'

services:
  ca.bc-coop.bclan:
    container_name: ca-bclan-network-it
    image: ghcr.io/komune-io/ssm-sandbox-ca:latest
    networks:
      - net

  orderer.bclan:
    container_name: orderer-network-it
    image: ghcr.io/komune-io/ssm-sandbox-orderer:latest
    networks:
      - net

  peer0.bc-coop.bclan:
    container_name: peer0-bclan-network-it
    image: ghcr.io/komune-io/ssm-sandbox-peer:latest
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=bclannet-it
    volumes:
      - /var/run/docker.sock:/host/var/run/docker.sock
    networks:
      - net
    depends_on:
      - orderer.bclan

  coop-rest-java:
    container_name: coop-rest-bclan-network-it
    image: ghcr.io/komune-io/ssm-sandbox-ssm-rest:latest
    ports:
      - 9090:9090
    networks:
      - net

networks:
  net:
    name: ${DOCKER_NETWORK}
    external: true