version: '3.7'

services:
  cli-init.bc-coop.bclan:
    container_name: cli-init-bclan-network-it
    image: ghcr.io/komune-io/ssm-sandbox-cli:latest
    command: /opt/commune-sandbox/util/init.sh
    networks:
      - net

networks:
  net:
    name: ${DOCKER_NETWORK}
    external: true