version: '3.8'

services:
  ca.bc-coop.bclan:
    container_name: ca-bclan-network-it
    image: ghcr.io/komune-io/hfabric-sandbox-ca:${VERSION}
    networks:
      - bclannet-it

  orderer.bclan:
    container_name: orderer-network-it
    image: ghcr.io/komune-io/hfabric-sandbox-orderer:${VERSION}
    networks:
      - bclannet-it

  peer0.bc-coop.bclan:
    container_name: peer0-bclan-network-it
    image: ghcr.io/komune-io/hfabric-sandbox-peer:${VERSION}
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=bclannet-it
    volumes:
      - /var/run/docker.sock:/host/var/run/docker.sock
    networks:
      - bclannet-it
    depends_on:
      - orderer.bclan

  coop-rest-java:
    container_name: coop-rest-bclan-network-it
    image: ghcr.io/komune-io/hfabric-sandbox-ssm-gateway:${VERSION}
    ports:
      - "9090:9090"
    networks:
      - bclannet-it


  cli-init.bc-coop.bclan:
    container_name: cli-init-bclan-network-it
    image: ghcr.io/komune-io/hfabric-sandbox-cli:${VERSION}
    command: /opt/commune-sandbox/chaincode/ssm/init.sh
    depends_on:
      - peer0.bc-coop.bclan
    networks:
      - bclannet-it

networks:
  bclannet-it:
    name: bclannet-it
