name: Dev

on: [push]

jobs:
  Dev:
    uses: komune-io/fixers-gradle/.github/workflows/dev-workflow.yml@e96cfe26d0391707479d59fe41f6908d3499a839
    permissions:
      contents: read
      packages: write
    with:
      makeDev: true
    secrets:
      GPG_SIGNING_KEY: ${{ secrets.GPG_SIGNING_KEY }}
      GPG_SIGNING_PASSWORD: ${{ secrets.GPG_SIGNING_PASSWORD }}
      PKG_MAVEN_USERNAME: ${{ secrets.PKG_MAVEN_USERNAME }}
      PKG_MAVEN_TOKEN: ${{ secrets.PKG_MAVEN_TOKEN }}
