name: Dev

on: [push]

jobs:
  Dev:
    uses: komune-io/fixers-gradle/.github/workflows/dev-workflow.yml@5b1c7563aee2a5a5419ea2e661d373cad97a5df4
    permissions:
      contents: read
      packages: write
    with:
      makeDev: true
    secrets:
      GPG_SIGNING_KEY: ${{ secrets.GPG_SIGNING_KEY }}
      GPG_SIGNING_PASSWORD: ${{ secrets.GPG_SIGNING_PASSWORD }}
      PKG_MAVEN_USERNAME: ${{ secrets.PKG_MAVEN_USERNAME }}
      PKG_MAVEN_TOKEN: ${{ secrets.PKG_MAVEN_TOKEN }}
