name: Dev

on: [push]

jobs:
  Dev:
    uses: komune-io/fixers-gradle/.github/workflows/dev-workflow.yml@7241cfc1464850e5c6918bd5aad53233113d258b
    permissions:
      contents: read
      packages: write
    with:
      makeDev: true
    secrets:
      GPG_SIGNING_KEY: ${{ secrets.GPG_SIGNING_KEY }}
      GPG_SIGNING_PASSWORD: ${{ secrets.GPG_SIGNING_PASSWORD }}
      PKG_MAVEN_USERNAME: ${{ secrets.PKG_MAVEN_USERNAME }}
      PKG_MAVEN_TOKEN: ${{ secrets.PKG_MAVEN_TOKEN }}
